### ISSUE TITLE
an example

### ISSUE THREAD

**Issue by remon** [epixa/chuckt#1]
I was using socket.io for few months but after facing firewalls and AV problems I decided to switch to sockjs and chuckt ,but in my application chuck event is sent to the same client not to all clients ,can you provide me with an example with sockjs

**Comment by epixa** [comment]
@remon Sorry for the delay in getting back to you.

At the moment, chuckt doesn't have a built-in equivalent to the socket.io `broadcast` functionality that allows the server to send out events to all socket connections at once.  In the absence of this functionality, you could do something like:

``` javascript
var chuckts = {};
function broadcast() {
  var args = arguments;
  Object.keys(chuckts).forEach(function(connid) {
    var chuckt = chuckts[connid];
    chuckt.emit.apply(chuckt, args);
  });
}

sock.on('connection', function(conn) {
  var chuckt = new ChuckT(conn);
  chuckts[conn.id] = chuckt;

  broadcast('new-client-connected'); // emits "new-client-connected" to all clients

  conn.on('close', function() {
    delete chuckts[conn.id];
  });
});
```

In this example, the broadcast function would proxy all arguments directly to the emit call on all sockjs connections.

Note that the behavior of `broadcast()` in this example is slightly different than socket-io in that it would emit the event to all clients _including_ the current client.  The broadcast function could be altered to take in an option "chuckt" object as the first argument and exclude the corresponding connection if present.

Also please beware, the above code is entirely untested.

I hope this helps!

**Comment by remon** [comment]
Thanks dear for your response ..I will test it and tell you how it's
working ..I was using socket.io for more than 6 months ..but i found its
not working with many users ...and then I read about its drawbacks with Avs
and firewalls ..thanks again

2013/10/25 Court Ewing notifications@github.com

**Comment by remon** [comment]
its working ..one last question how can you implement something like
socket.set and socket.get with sockjs and chuckt.js ?

2013/10/25 Remon torremolinos remmony@gmail.com

**Comment by epixa** [comment]
The set/get functions in socket.io aren't really related to websockets at all, they're just an extra feature that was added to that library.  If you're using the default MemoryStore backend for set/get in socket.io, then you could always just add whatever properties you want directly to the chuckt object.

If you're using a different store (e.g. redis), then its more complicated, and there is no built in solution to chuckt or sockjs.

**Comment by remon** [comment]
I am using socket.io get and set to handle user id ,so when user open I
retrieve some data from redis using his id and also when he close the
connection

2013/10/27 Court Ewing notifications@github.com

**Comment by epixa** [comment]
In that case, you would need to implement a solution for that manually.
